- name: Update OPKG
  shell: opkg update
  when: ansible_pkg_mgr == 'opkg'

- name: Install packages
  shell: opkg install libffi python3-yaml python3-pyserial python3-distutils python3-cryptography python3-pip python3-setuptools python3-dev unzip grep libustream-openssl bash
  when: ansible_pkg_mgr == 'opkg'

- name: Install packages
  ansible.builtin.apt:
    name:
      - python3-cryptography
      - python3-pip
      - python3-setuptools
      - python3-dev
      - python3-yaml
      - python3-serial
      - python3-distutils
      - python3-qrcode
      - unzip
      - grep
    state: present
    update_cache: yes
  when: ansible_pkg_mgr == 'apt'
  become: true

- name: Install python packages
  ansible.builtin.pip:
    name:
      - setuptools
      - wheel
      - reedsolo
      - pexpect
      - enum-compat
      - dotmap
      - click
      - ecdsa
    executable: pip3
    extra_args: "{{ (ansible_distribution == 'Kali' or (ansible_distribution == 'Debian' and ansible_distribution_release == 'bookworm')) | ternary('--break-system-packages', omit) }}"

- name: Install python meshtastic, esptool
  ansible.builtin.pip:
    name:
      - meshtastic
      - esptool
    state: latest
    executable: pip3
    extra_args: "{{ (ansible_distribution == 'Kali' or (ansible_distribution == 'Debian' and ansible_distribution_release == 'bookworm')) | ternary('--break-system-packages', omit) }}"

# ToDo: move to common
- name: Getting hardware model
  shell: "meshtastic --info {{ '--port ' + hostvars['self']['cyport'] if 'CYGWIN' in ansible_distribution else '' }} | grep -oP '(?<=\"hwModel\": \")[^\"]+' | head -1"
  register: msh_model_detect
  when: "hw is not defined"

- name: Redefine model var (detected)
  set_fact:
    msh_model: "{{ msh_model_detect.stdout }}"
  when: "hw is not defined"

- name: Redefine model var (manual)
  set_fact:
    msh_model: "{{ hw }}"
  when: "hw is defined"

- name: Looking for lastest release
  local_action:
    module: ansible.builtin.uri
    url: https://api.github.com/repos/meshtastic/Meshtastic-device/releases
    return_content: true
  register: github_response

- name: Creating TEMP dir (LOCAL)
  local_action:
    module: ansible.builtin.file
    path: "{{ msh.fw.temp }}"
    state: directory

- name: "Getting {{ github_response.json.0.tag_name }}"
  loop: "{{ github_response.json.0.assets }}"
  local_action:
    module: ansible.builtin.unarchive
    src: "{{ item.browser_download_url }}"
    remote_src: yes
    keep_newer: yes
    dest: "{{ msh.fw.temp }}"
  when: "'firmware-' in item.name"

- name: Connected device is TTGO-LORA v1
  set_fact:
    msh_firmware: "firmware-tlora-v1-{{ github_response.json.0.tag_name | regex_replace('^v(.*)$', '\\1') }}"
  when: "msh_model == 'TLORA_V1'"

- name: Connected device is TTGO-LORA v1.3
  set_fact:
    msh_firmware: "firmware-tlora_v1_3-{{ github_response.json.0.tag_name | regex_replace('^v(.*)$', '\\1') }}"
  when: "msh_model == 'TLORA_V1_1P3'"

- name: Connected device is TBEAM
  set_fact:
    msh_firmware: "firmware-tbeam-{{ github_response.json.0.tag_name | regex_replace('^v(.*)$', '\\1') }}"
  when: "msh_model == 'TBEAM'"

- name: Connected device is RAK4631
  set_fact:
    msh_firmware: "firmware-rak4631-{{ github_response.json.0.tag_name | regex_replace('^v(.*)$', '\\1') }}"
  when: "msh_model == 'RAK4631'"

- name: Creating TEMP dir (REMOTE)
  ansible.builtin.file:
    path: "{{ msh.fw.temp }}-install"
    state: directory

- name: Copy firmware to remote
  ansible.builtin.copy:
    src: "{{ msh.fw.temp }}/{{ item }}"
    dest: "{{ msh.fw.temp }}-install/{{ item }}"
    mode: 0755
  with_items:
    - "device-install.sh"
    - "bleota.bin"
    - "{{ msh_firmware }}.bin"
    - "{{ msh_firmware }}-ota.zip"
    - "littlefs-{{ github_response.json.0.tag_name | regex_replace('^v(.*)$', '\\1') }}.bin"
    - "{{ msh_firmware }}-d.bin"
    - "littlefs-{{ github_response.json.0.tag_name | regex_replace('^v(.*)$', '\\1') }}-d.bin"

  when: "msh_firmware is defined"
  failed_when: false
  no_log: true

- name: Upgrading firmware (ESP32)
  ansible.builtin.shell: "bash ./device-install.sh -f {{ msh_firmware }}*.bin"
  args:
    chdir: "{{ msh.fw.temp }}-install"
  register: device_install
  when: "msh_firmware is defined and msh_model != 'RAK4631'"

- name: Install python packages required for RAK4631
  ansible.builtin.pip:
    name:
      - adafruit-nrfutil
      - click==7.0
    executable: pip3
    extra_args: "{{ (ansible_distribution == 'Kali' or (ansible_distribution == 'Debian' and ansible_distribution_release == 'bookworm')) | ternary('--break-system-packages', omit) }}"
  when: "msh_firmware is defined and msh_model == 'RAK4631'"

- name: Rebooting device
  shell: "meshtastic --reboot {{ '--port ' + hostvars['self']['cyport'] if 'CYGWIN' in ansible_distribution else '' }}"
  when: "msh_firmware is defined and msh_model == 'RAK4631'"

- name: Sleep for 20 seconds
  ansible.builtin.wait_for:
    timeout: 20
  when: "msh_firmware is defined and msh_model == 'RAK4631'"

- name: Upgrading firmware (RAK4631)
  shell: "adafruit-nrfutil --verbose dfu serial  {{ '--port ' + hostvars['self']['cyport'] if 'CYGWIN' in ansible_distribution else '--port /dev/ttyACM0' }} -b 115200 --singlebank --touch 1200 --package {{ msh_firmware }}-ota.zip"
  args:
      chdir: "{{ msh.fw.temp }}-install"
      executable: /bin/bash
  register: device_install
  when: "msh_firmware is defined and msh_model == 'RAK4631'"
- name: OUTPUT
  debug:
    var: device_install.stdout_lines

- name: Remove TEMP dir (REMOTE)
  ansible.builtin.file:
    path: "{{ msh.fw.temp }}-install"
    state: absent
